### ISSUE TITLE
NC 28 Support

### ISSUE THREAD

**Issue by petedenison** [major-mayer/imageconverter#13]
Please add Official Support for Nextcloud Version 28

**Comment by major-mayer** [comment]
Hi, I'm working on it, but i need some more time.
Nextcloud 28 introduces a lot of changes how apps that use file actions are registered and apparently also what is exposed in the OCA.Files namespace.
https://docs.nextcloud.com/server/latest/developer_manual/app_publishing_maintenance/app_upgrade_guide/upgrade_to_28.html

This is why this time a simple version bump is not enough and the app doesn't work anymore with Nextcloud 28.
Thank you for your patience.

**Comment by bcutter** [comment]
@major-mayer Can you give at least a (rough) estimation on the time you need to restore compatibility? Thx.

**Comment by major-mayer** [comment]
Yeah sorry, should be done in the next 1-2 weeks.
I was quite a lot on vacations the last weeks.

**Comment by bcutter** [comment]
That's great news. You'll make many (existing or future/currently waiting to update) NC v28 users happy :-)

**Comment by major-mayer** [comment]
All right, this was much more work than initially expected, especially because the new Files APIs and especially events are really badly documented. 
But finally I managed to solve all the obstacles that popped up during development and just released version 2.0.0 which is basically a complete rewrite of the frontend part.
Things work a bit different now, but since I don't have access to the old `OCA.Files` APIs anymore in Nextcloud 28, there is no other way to do it.

On the plus side, the conversion action for multiple files is now only shown, when there are only HEIF/HEIC images in the selection, this was not possible before.
Hope you like it and don't encounter too many bugs  :slightly_smiling_face:

**Comment by bcutter** [comment]
Thank you for your work @major-mayer !

Unfortunately...

https://github.com/major-mayer/imageconverter/issues/14

**Comment by major-mayer** [comment]
Should be fixed now, sorry for the inconvenience.

**Comment by major-mayer** [comment]
Maybe a bit of self-advertisement:
If you like my app and the effort that I put into it, please consider rating in the [Nextcloud app store](https://apps.nextcloud.com/apps/imageconverter). 
I've just discovered that I only have 3/5 stars :cry:

**Comment by bcutter** [comment]
Feel free :-) I'd like to vote.

But one needs to have a Nextcloud AppStore account to vote?

**Comment by major-mayer** [comment]
Yeah, unfortunately that's a requirement

**Comment by petedenison** [comment]
Thank you for your work on the upgrade.
